"""Build a small playback index and apply checked, repeatable Flutter-build hooks.

Run again after replacing main.dart.js with a new Flutter build. Unknown build
shapes fail without writing the bundle, rather than silently patching wrong code.
"""
import json
from pathlib import Path

from generate_audio import ROOT, read_json

HOOKS = {
    'v.G.speechSynthesis.cancel()': '(v.G.verbalingoSpeech||v.G.speechSynthesis).cancel()',
    'v.G.speechSynthesis.pause()': '(v.G.verbalingoSpeech||v.G.speechSynthesis).pause()',
    'r.speechSynthesis.resume()': '(r.verbalingoSpeech||r.speechSynthesis).resume()',
    'r.speechSynthesis.speak(s)': '(r.verbalingoSpeech||r.speechSynthesis).speak(s)',
    's.speechSynthesis.pause()': ';(s.verbalingoSpeech||s.speechSynthesis).pause();',
    's.speechSynthesis.resume()': ';(s.verbalingoSpeech||s.speechSynthesis).resume();',
    'ano(a){var s,r,q,p,o=this':
        'ano(a){if(v.G.verbalingoSpeech&&v.G.verbalingoSpeech.hasRecordings&&/^de(?:[-_]|$)/i.test(a))return!0;var s,r,q,p,o=this',
}

# Sentence translation and cued-recall hints now come from the Dart source.


def patch_bundle(source):
    result = source
    for old, new in HOOKS.items():
        if result.count(new) == 1:
            continue
        if result.count(old) != 1:
            raise ValueError(f'Unsupported Flutter build: expected exactly one {old!r}')
        result = result.replace(old, new)
    return result


def main():
    manifest = read_json(ROOT / 'audio/de-DE/manifest.json')
    if not manifest['complete']:
        raise SystemExit('Generate and verify the full audio set before installing it')
    index = {}
    for entry in manifest['entries']:
        filename = entry['file']
        if Path(filename).name != filename or filename not in manifest['files']:
            raise ValueError(f'Invalid file for {entry["id"]}')
        audio = ROOT / 'audio/de-DE' / filename
        if not audio.is_file():
            raise ValueError(f'Missing audio: {filename}')
        text = ' '.join(entry['text'].split())
        index[text] = 'audio/de-DE/' + filename
    bundle = ROOT / 'main.dart.js'
    patched = patch_bundle(bundle.read_text(encoding='utf-8'))
    html_path = ROOT / 'index.html'
    html = html_path.read_text(encoding='utf-8')
    loader = '  <script src="flutter_bootstrap.js" async></script>'
    scripts = '  <script src="audio/de-DE/playback-index.js"></script>\n  <script src="recorded-speech.js"></script>\n'
    if 'src="recorded-speech.js"' not in html:
        if html.count(loader) != 1:
            raise ValueError('Expected exactly one Flutter bootstrap script')
        html = html.replace(loader, scripts + loader)
    payload = json.dumps(index, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')
    (ROOT / 'audio/de-DE/playback-index.js').write_text(
        '// Generated by tools/install_site_audio.py; do not edit.\nwindow.verbalingoAudioIndex=' + payload + ';\n', encoding='utf-8')
    bundle.write_text(patched, encoding='utf-8')
    html_path.write_text(html, encoding='utf-8')
    print(f'Installed {len(index)} recordings for {len(manifest["entries"])} exercises')


if __name__ == '__main__':
    main()
